{% set name = "wkhtmltopdf" %}
{% set major_minor = "0.12" %}
{% set version = major_minor + ".5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: wkhtmltox-{{ version }}_linux-generic-amd64.tar.xz  # [linux]
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz  # [linux]
  sha256: 861d6e61e2f5beb2d8daaade2cd5a85b84065ee9fac0d6d85000d8a7712a4621  # [linux]

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  run:
    - fontconfig
    - xorg-libxrender
    - xorg-libxext

test:
  commands:
    - wkhtmltopdf -h

about:
  home: http://wkhtmltopdf.org/
  license: LGPLv3
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Command line tools to render HTML into PDF and various image formats.'
  description: |
    wkhtmltopdf and wkhtmltoimage are open source (LGPLv3) command line tools
    to render HTML into PDF and various image formats using the Qt WebKit rendering engine.

extra:
  recipe-maintainers:
    - scopatz
