context:
  name: wkhtmltopdf
  major_minor: "0.12"
  version: ${{ major_minor }}.6
  pkg_release: "1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: win
    then:
      file_name: wkhtmltox-${{ version }}-${{ pkg_release }}.msvc2015-win64.exe
      url: https://github.com/${{ name }}/packaging/releases/download/${{ version }}-${{ pkg_release }}/wkhtmltox-${{ version }}-${{ pkg_release }}.msvc2015-win64.exe
      sha256: 1efcfaf8472871268fd399865a3e62b435b91d4413009b80830eaaff7a57d088

build:
  number: 0
  skip:
    - osx
    - linux

requirements:
  build:
    - if: win
      then:
        - 7zip
  run:
    - if: win
      then:
        - vc >=14

tests:
  - script:
      - wkhtmltopdf -h

about:
  homepage: http://wkhtmltopdf.org/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Command line tools to render HTML into PDF and various image formats.
  description: |
    wkhtmltopdf and wkhtmltoimage are open source (LGPLv3) command line tools
    to render HTML into PDF and various image formats using the Qt WebKit rendering engine.

extra:
  recipe-maintainers:
    - scopatz
