travis:
  secure:
    BINSTAR_TOKEN: QwUjpKF+eJ34HWJiU013VNlw0jdC+mDWChSGlCYd/7DPTim79+Vjq1zHUMl6MobdTlKtOLGU6ws6AQr7Ci6mTeYVnpytR86/PZnHB02Lx3iHboVWdqvDkFguHKgmzYM72Nz6kB98EQ2wjkGUL0I4P7IBh9+QFKnxKpPfqL0IYvapNmO/1b0HEHSbGkNH/imxJre4RTxQ+kChVW/TeATrd6qk1O3EeDgBugYYAoLSw4VWapYqcrrnpzj2Nk98mfOWHnk0xvO9M7xIHXPpBR85H+U3h+V6q20KPe62K74SglIZKtddijSknfIXlPtRZZbmg0KOkp2RXMvlcS97Tw8GLwxeoqTXaqNzgARW7CvMLFxZJ+QmBVu8J3KMtAlqQQWqvupPTteBw/UcUZfjYRAhjxKJX6aPRrT7er4pHinFc+hBigTVfDClHTzMerMi6OVth3drSTp1d++6zPriHc7PdOcY1pSJ47QXmEObMw2cW35mwx1D9wfjcLK2tgClXHVHHzMLFcrqOu0HuEP8j8mJVifACAHAny/gR9dFR0I+qT+uOvntD664tyt04fBILk2qZgUfCk0icEtplyxLCMkExaqnkaOIFNRmMzFbIyuebux9vGWSEOf/YF1QNgqYEXrTuwk6afwmQkxFzSNCDyUGKe7HkjtBg/rxqDXuUuKDoxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
