travis:
  secure:
    BINSTAR_TOKEN: SXR+Lto0g/E+zre+tLKkxJXXlm4Ew5Wer9wpIIzTX6TpoGGXBW/CNKYAAPmjkA9ydvnwnKxoMeYGftFf/jGxu7fe36pGnmEerIg/l0mxFZNDvK3iZTOg+qS+clGo+89fXV4hHWnruLIzhOXSvwHm3WKVhOHjRZ6wUavloXRExermdyJXJv+pZZa8yVPh+TVqNPaHvT+nmU4/oQGPnPCurglijohk/fKfnEdo7NP+e8PoiEf7jr/x2DlHgdi0TD1aQ/furyj26jh0PZyamliDXJ8kt7DOpPp6lnZ0XDlmWauBbxKNVvbJNGfhGZScZcmS95sYoWEGW69tGAinfqQG/DWB818i2yqv39k+WzOR/6aO6bRhT6N4Caw4RjB2I1e8//U18T0oGA9KjRL864swsyOsaOomUie85UwJ+haBXIL4/HOO1q+PnQTuUUlM/KYCKhtlPhSzjbknIM6o+D77ImkytnMOSV4ti6JlljhGSM5Miv1E8fpru+b5ZLQlytYLKr7MFp5fE9xe0Y04YiHhBBVQyz0XxqEb+20yB/3nUV/SyFaQcP3h3DCP9nhauS2Z8SwHRKp87S6eBj58sVlpDFAp+DE/UFJpL+CK/Sl0tP5kXfLUvPET/XNrPQHhkg8OHEERKVr0jQhCxsqn7/bcxxS0Yv1jXU6RYJIQTf1WaqE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
